INSERT INTO USER (USERNAME, PASSWORD) VALUES ('administrator','$2a$10$y43pfhNT9RgnMhnvRKSccuBxdV2dFeorcTEHBsBl//bz10wxhACVe');
INSERT INTO ROLE (NAME) VALUES ('ADMIN');
INSERT INTO USER_ROLES VALUES (1,1)
